# Convert a 1D array to a 2D array with 2 rows?




In [1]:
import numpy as np


In [3]:
arry=np.arange(10)
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arry=arry.reshape((2,5))

In [8]:
arry.ndim

2

# Question:2
How to stack two arrays vertically?

In [12]:
arry2=np.array(([1,1,1,1,1],[1,1,1,1,1]))
np.vstack((arry,arry2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3
How to stack two arrays horizontally?¶

In [14]:
np.hstack((arry,arry2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Question:5
How to Convert higher dimension into one dimension?

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15]).reshape((3,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
arr=arr.flatten()

# Question:6
Convert one dimension to higher dimension?

In [28]:
arr.reshape((5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

#  Question:7
Create 5x5 an array and find the square of an array? 

In [30]:
arr55=np.arange(25).reshape((5,5))
arr55

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Question:8
Create 5x6 an array and find the mean?

In [32]:
arr56=np.arange(30).reshape((5,6))
arr56

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [33]:
np.mean(arr56)

14.5

# Question:9
Find the standard deviation of the previous array in Q8?¶

In [34]:
np.std(arr56)

8.65544144839919

# Question:10
Find the median of the previous array in Q8

In [35]:
np.median(arr56)

14.5

# Question:11
Find the transpose of the previous array in Q8?

In [36]:
np.transpose(arr56)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Question:12
Create a 4x4 an array and find the sum of diagonal elements?

In [41]:
ar=np.arange(16).reshape((4,4))
np.trace(ar)

30

# Question:13
Find the determinant of the previous array in Q12?# 

In [48]:

np.linalg.det(ar)

-2.9582283945787796e-30

# Question:14
Find the 5th and 95th percentile of an array?

In [49]:
np.percentile(ar,5)

0.75

In [50]:
np.percentile(ar,95)

14.25

# Question:15
How to find if a given array has any null values?

In [53]:
ar=np.array([np.nan])
ar

array([nan])

In [54]:
np.isnan(ar)

array([ True])